name: Run the integration tests

on:
    push:
        # branches:
        #     - main

jobs:
    integrationtests:
        runs-on: ubuntu-latest
        steps:
            # Checkout the Repo
            - uses: actions/checkout@v2

            # Install Node 18
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 18

            # Install dependencies
            - run: npm install

            # Run tests
            - run: npm test
